version: '3.8'

services:
  reflex_app:
    build: .
    container_name: reflex_app
    ports:
      - "3001:3000"
    environment:
      - DATABASE_PATH=/app/data/app.db
    volumes:
      - ./data:/app/data
      - ./nueva_app_reflex:/app/nueva_app_reflex
    command: reflex run --env prod --backend-host 0.0.0.0
