version: '3.8'

services:
  reflex_app:
    build: .
    container_name: reflex_app
    ports:
      - "3005:3000"
    environment:
      - DATABASE_PATH=/app/data/app.db
    volumes:
      - ./data:/app/data
    command: reflex run --env dev --backend-host 0.0.0.0
