version: '3.8'

services:
  reflex_app:
    build: .
    container_name: reflex_app
    ports:
      - "3005:3000"
    command: reflex run --backend-host 0.0.0.0
    volumes:
      - ./data:/app/data
